name: Close Stale Issues

on:
  schedule:
    - cron: '0 0 * * *'
  issues:
    types: [opened, edited, labeled, unlabeled]

jobs:
  close-stale:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues
        uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 180 # Mark as stale after 180 days of inactivity
          days-before-close: 14  # Close issue if no activity after 14 days of being stale
          days-before-pr-close: -1
          stale-issue-label: Stale         # This setting defines the label that will be applied to issues that are considered stale
          exempt-issue-labels: Low Priority
          stale-issue-message: >
            This issue has been automatically marked as stale due to inactivity.
            If it remains inactive for another 7 days, it will be closed.
          close-issue-message: >
            This issue is now closed due to prolonged inactivity.
          operations-per-run: 30           # This setting specifies the maximum number of operations (such as marking issues as stale or closing them) that the action will perform in a single run
          close-issue-reason: not_planned  # This setting specifies the reason that will be given when closing stale issues
