name: Run Tests

on: 
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 21

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test